---
# List of package dependencies.
os_images_package_dependencies:
  - "{% if os_images_rhel_debootstrap_enabled | bool %}debootstrap{% endif %}"
  - dosfstools
  - gdisk
  - "{% if os_images_git_elements | length > 0 %}git{% endif %}"
  - kpartx
  - lvm2
  - python3-devel
  - qemu-img
  - squashfs-tools
  - xz
