---
# Path to a directory in which to create a virtualenv.
os_deploy_templates_venv:

# Upper constraints file for installation of Python dependencies.
os_deploy_templates_upper_constraints_file: https://releases.openstack.org/constraints/upper/2023.1

# Authentication type.
os_deploy_templates_auth_type:
# Authentication information.
os_deploy_templates_auth: {}
# Endpoint URL type to fetch from the service catalog. Maybe be one of:
# public, admin, or internal.
os_deploy_templates_interface:
# List of Ironic deploy templates to register. Each item should be a dict
# containing the following items:
# - 'name': Name of the deploy template. Required when the deploy template is
#           created, after which the name or ID may be used.  - 'steps': List
#           of deploy steps.
# - 'extra': Dict of metadata, optional.
# - 'uuid': UUID, optional.
# - 'state': State, optional.
os_deploy_templates: [] # noqa var-naming[no-role-prefix]
